name: Check versions

on:
  push:
    tags:
      - v*

jobs:
  semver-checks:
    runs-on: ubuntu-latest

    name: cargo semver-checks
    steps:
      - uses: actions/checkout@v4
      - uses: obi1kenobi/cargo-semver-checks-action@v2
