name: Publish new version

on:
  release:
    types: [created]

jobs:
  semver-checks:
    runs-on: ubuntu-latest

    name: cargo semver-checks
    steps:
      - uses: actions/checkout@v4
      - uses: obi1kenobi/cargo-semver-checks-action@v2

  publish-crate:
    runs-on: ubuntu-latest
    needs: semver-checks

    name: Build and publish to crates.io
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - run: cargo publish --token ${{ secrets.CRATES_IO_TOKEN }}
